# Generated by Django 4.2.2 on 2023-07-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgtest',
            name='msg',
            field=models.TextField(),
        ),
    ]
