# Generated by Django 4.2.3 on 2023-07-10 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('msg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
