# Generated by Django 4.2.2 on 2023-07-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_alter_display_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='user_id',
        ),
    ]
