# Generated by Django 4.2.2 on 2023-07-15 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_remove_display_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='msg_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
